name: Run unit tests
on:
  push:
    branches:
      - main

jobs:
  main:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: abatilo/actions-poetry@v2
      - name: Install build dependencies (${{ runner.os }})
        if: runner.os == 'Linux'
        run: sudo apt-get install ninja-build clang
      - name: Install Conan
        run: |
          poetry install
          poetry run conan version
      - name: Install Conan dependencies
        run: poetry run conan install . --profile:all=./.conan2/profiles/${{ runner.os }} --output-folder=build --build=missing
      - name: Dump Conan cache manifest
        run: conan list "*" --format=json > conan-cache.json
      - name: Cache Conan dependencies
        uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-${{ hashFiles('**/conan-cache.json') }}
